language: node_js
services:
  - redis-server
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  # Currently these versions are disabled because blanket does not support them
  #- "0.8"
  #- "0.6"
script:
  - npm run coverage
after_script:
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
