name: Authenticating Proxy
processName: auth-proxy
host: 127.0.0.1
cookieDomain: false
port: 443
# Set this to `false` to not listen on HTTP.
httpPort: 80
sslCert: /usr/lib/node_modules/auth-proxy/test/ssl/cert.pem
sslKey: /usr/lib/node_modules/auth-proxy/test/ssl/key.pem
redisHost: 127.0.0.1
redisPort: 6379
sessionSecret: secret
imageURL: 'http://nodejs.org/images/logos/nodejs.png'
imageAlt: Node.js logo
authenticationStrategies: {}
verbose: false
loginPath: /login
logoutPath: /proxy-logout
indexPath: /
routeWhiteList:
  - '/css/bootstrap.css'
  - '/img/glyphicons-halflings.png'
authenticationStrategies:
  GoogleOAuth2:
    # Note this option does not work with `@gmail.com` addresses, you would need to leave it empty.
    allowedDomains: zivtech.com
    # Note if you leave this empty and populate only the domain everyone in your apps domain will have access.
    allowedEmails: false
    googleClientId: 928519207178-qed3gidg37rbqfmsisbe0l6p1bqdk8c4.apps.googleusercontent.com
    googleClientSecret: 8aO5hCAKcWabCA-KfxtTWPJ1