authenticationStrategies:
  GoogleOAuth2:
    # Note this option does not work with `@gmail.com` addresses, you would need to leave it empty.
    allowedDomains: YOUR_DOMAINS
    # Note if you leave this empty and populate only the domain everyone in your apps domain will have access.
    allowedEmails: YOUR_EMAILS
    googleClientId: CHANGE ME
    googleClientSecret: CHAGNE ME
   
